// Channel names, defined once so main and preload can never drift.
export const IPC = {
  settingsGet: "settings:get",
  settingsSet: "settings:set",
  settingsStatus: "settings:status",
  jiraTest: "jira:test",
  jiraProjects: "jira:projects",
  jiraAssignees: "jira:assignees",
  jiraBoards: "jira:boards",
  jiraCreate: "jira:create",
  // The tester's queue: what is waiting for QA, and acting on it in place.
  jiraStatuses: "jira:statuses",
  jiraQueue: "jira:queue",
  jiraIssue: "jira:issue",
  jiraTransitions: "jira:transitions",
  jiraTransition: "jira:transition",
  jiraComment: "jira:comment",
  jiraAttachment: "jira:attachment",
  llmReview: "llm:review",
  windowNew: "window:new",
  authRequest: "auth:request",
  authRespond: "auth:respond",
  authCount: "auth:count",
  authForget: "auth:forget",
  workspaceGet: "workspace:get",
  workspaceSet: "workspace:set",
  clipboardWrite: "clipboard:write",
  clipboardImage: "clipboard:image",
  openExternal: "shell:open",
} as const;
